server:
  port: ${PORT:8080}

spring:
  application:
    name: URL-Shortener

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/url_shortener}
    username: ${SPRING_DATASOURCE_USERNAME:url_shortener_user}
    password: ${SPRING_DATASOURCE_PASSWORD:url_shortener_pass}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6380}

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE:PEM}
      ssl.truststore.certificates: ${KAFKA_SSL_TRUSTSTORE_CERTIFICATES:}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1

    consumer:
      group-id: analytics-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  profile-image-dir: ${TRIMLY_PROFILE_IMAGE_DIR:${user.home}/.trimly/profile-images}
  public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  rate-limit:
    requests-per-minute: ${RATE_LIMIT:20}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO

google:
  client-id: ${GOOGLE_CLIENT_ID:}
