-- Trimly v1 baseline.
-- Represents the actual PostgreSQL schema at the point Flyway
-- becomes the authoritative schema migration mechanism.

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255),
    token_version BIGINT NOT NULL DEFAULT 0,
    full_name VARCHAR(120),
    profile_image_url VARCHAR(500),
    default_link_expiration VARCHAR(20) NOT NULL DEFAULT 'never',
    google_subject VARCHAR(255),
    auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    created_at TIMESTAMP
);

CREATE UNIQUE INDEX uk_users_email
    ON users (email);

CREATE UNIQUE INDEX uk_users_google_subject
    ON users (google_subject)
    WHERE google_subject IS NOT NULL;


CREATE TABLE urls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    long_url VARCHAR(2048) NOT NULL,
    short_url VARCHAR(8),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    expires_at TIMESTAMP,
    active BOOLEAN NOT NULL,
    owner_id INTEGER,

    CONSTRAINT uk_urls_short_url UNIQUE (short_url),
    CONSTRAINT fk_urls_owner
        FOREIGN KEY (owner_id)
        REFERENCES users (id)
);


CREATE TABLE click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clicked_at TIMESTAMP NOT NULL,
    ip_address VARCHAR(45),
    short_url VARCHAR(255) NOT NULL,
    user_agent VARCHAR(255)
);


CREATE TABLE user_two_factor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    enabled_at TIMESTAMP,
    pending_secret VARCHAR(128),
    secret VARCHAR(128),
    user_id INTEGER NOT NULL,

    CONSTRAINT uk_user_two_factor_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_two_factor_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);


CREATE TABLE two_factor_recovery_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash VARCHAR(255) NOT NULL,
    used BOOLEAN NOT NULL,
    used_at TIMESTAMP,
    version BIGINT NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT fk_recovery_codes_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE INDEX idx_recovery_codes_user
    ON two_factor_recovery_codes (user_id);
